[package]
name = "mock-usdc"
version = "1.0.0"
authors = ["Akbar Idria <akbaridria15@gmail.com>"]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "6f83bc6d02207298b2dee91133d75538789bf582" }

[addresses]
mock_usdc = "_"