export const FLASHBET_ABI = {
  address: "0xab113bc33b4376ec543703c357d821eae860e447353bed8efb2e84ef6045958e",
  name: "flashbet_core",
  friends: [],
  exposed_functions: [
    {
      name: "get_user_bets",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["0x1::option::Option\u003Cvector\u003Cu64\u003E\u003E"],
    },
    {
      name: "place_bet",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "u64",
        "u64",
        "bool",
        "u64",
        "vector\u003Cvector\u003Cu8\u003E\u003E",
      ],
      return: [],
    },
    {
      name: "resolve_bet",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "vector\u003Cvector\u003Cu8\u003E\u003E"],
      return: [],
    },
    {
      name: "get_vault_balance",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u64"],
    },
    {
      name: "add_liquidity",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "get_provider_liquidity",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: [
        "0x1::option::Option\u003C0xb2f01c24171f7dc1b138b4e020aa9f29f2811b99aba5b833fb9c75061da1c795::reward_distributor::ProviderBalance\u003E",
      ],
    },
    {
      name: "remove_liquidity",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "get_bet_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["u64"],
      return: [
        "0x1::option::Option\u003C0xb2f01c24171f7dc1b138b4e020aa9f29f2811b99aba5b833fb9c75061da1c795::bet_manager::Bet\u003E",
      ],
    },
    {
      name: "get_market_state",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u64", "u64", "bool"],
    },
    {
      name: "mint_usdc",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
  ],
  structs: [
    {
      name: "Flashbet",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "pyth_btc_price_id",
          type: "vector\u003Cu8\u003E",
        },
        {
          name: "is_paused",
          type: "bool",
        },
      ],
    },
  ],
} as const;
